Update README files
NOAA-EMC/GSI-Monitor pull request #79
Opened 2023-04-21 12:33 UTC by EdwardSafford-NOAA

Update README files in GSI-monitor to reflect current reality.

Resolves #76

2023-05-24 16:01 UTC, EdwardSafford-NOAA commented
Add examples of command line specifications, especially for -t|--tank.

2023-05-24 20:07 UTC, ADCollard requested changes
So I've suggested a small number of changes.   I have only gone through the RadMon process for now, but the other READMEs look OK (some of the RadMon changes apply to the other components too)

2023-05-24 20:07 UTC, ADCollard commented on README.md
>  These tools monitor the Gridpoint Statsical Interpolation (GSI) package's data assimiliation, detecting
"Statistical"

2023-05-24 20:07 UTC, ADCollard commented on src/Radiance_Monitor/README
> +                        It must be in YYYYMMDDHH format.
Can you specify that this is the FINAL cycle for which images will be generated (i.e, it is this cycle and `ncyc` cycles before this one).

2023-05-24 20:07 UTC, ADCollard commented on src/Radiance_Monitor/README
> +
Maybe add usage for Run_Transfer.sh?

2023-05-24 20:07 UTC, ADCollard commented on src/Radiance_Monitor/README
> +
Also WEBUSER?

What about MAIL_TO in `src/Radiance_Monitor/parm/RadMon_user_settings`?

2023-05-24 20:07 UTC, ADCollard requested changes
So I've suggested a small number of changes.   I have only gone through the RadMon process for now, but the other READMEs look OK (some of the RadMon changes apply to the other components too)

2023-05-25 20:03 UTC, EdwardSafford-NOAA commented on README.md
>  These tools monitor the Gridpoint Statsical Interpolation (GSI) package's data assimiliation, detecting
Done.

2023-05-25 20:03 UTC, EdwardSafford-NOAA commented on src/Radiance_Monitor/README
> +                        It must be in YYYYMMDDHH format.
Done, and for other READMEs as well.

2023-05-25 20:04 UTC, EdwardSafford-NOAA commented on src/Radiance_Monitor/README
> +
Done, and for others as well.

2023-05-25 20:04 UTC, EdwardSafford-NOAA commented on src/Radiance_Monitor/README
> +
Done.

2023-06-01 18:55 UTC, ADCollard approved these changes

2023-06-01 19:07 UTC, merged